In [1]:
import pandas as pd
import numpy as np
import importlib

from tqdm import tqdm

import plotly.graph_objects as go
import plotly.express as px
from plotly.colors import qualitative

from irina import utility_functions as uf

In [2]:
importlib.reload(uf)

# Test Statistics

In [ ]:
df_country_stats_compare

df_interest_metric
df_interest_metric_individual

df_subfields_stats
df_subfields_stats_individual

df_interest_metric_stats
df_interest_metric_individual_stats

df_distance
df_distance_individual

df_distance_stats
df_distance_individual_stats

In [32]:
year = 2000
df_country_subfield_collab = pd.read_csv(uf.PATH+"df_country_subfield/collaborative_"+str(year)+".csv", index_col=0)
df_country_subfield_indiv = pd.read_csv(uf.PATH+"df_country_subfield/individual_"+str(year)+".csv", index_col=0)

In [33]:
df_country_stats_collab = uf.get_country_stats(df_country_subfield_collab)
df_country_stats_indiv = uf.get_country_stats(df_country_subfield_indiv)

In [35]:
col_list_coupled = [[col+"_collab", col+"_indiv"] for col in df_country_stats_collab.columns.to_list()]
col_list = [x for sublist in col_list_coupled for x in sublist]

df_country_stats_compare = (
    df_country_stats_collab
    .merge(df_country_stats_indiv, left_index=True, right_index=True, how="outer", suffixes=("_collab", "_indiv"))
    [col_list]
    .assign(year=year)
    .reset_index()
)

In [36]:
df_interest_metric_collab = uf.get_interest_metric(df_country_subfield_collab)
df_interest_metric_indiv = uf.get_interest_metric(df_country_subfield_indiv)

In [45]:
df_subfield_stats_collab = uf.get_subfield_stats(df_country_subfield_collab, df_interest_metric_collab, year)
df_subfield_stats_indiv = uf.get_subfield_stats(df_country_subfield_indiv, df_interest_metric_indiv, year)

In [46]:
uf.get_subfield_info(2605)

      subfield_id              subfield_name   field_name        domain_name
2302         2605  Computational Mathematics  Mathematics  Physical Sciences

In [47]:
df_interest_metric_stats_collab

,country,std_val,count_subfield_0_25,count_subfield_25_50,count_subfield_50_75,count_subfield_75_100,top1_subfield,top2_subfield,top3_subfield,top4_subfield,top5_subfield,year
0,AE,0.933973,6,6,18,32,3004,2731,2611,1102,2212,2000
1,AF,NaN,0,0,0,1,3320,1100,1102,1103,1104,2000
2,AG,0.784636,0,0,0,3,2745,2728,2746,1100,1102,2000
3,AL,1.254012,0,0,3,12,1502,3318,1603,1904,1109,2000
4,AM,1.063817,7,11,12,22,2702,3102,3404,1304,1711,2000
...,...,...,...,...,...,...,...,...,...,...,...,...
197,WS,1.518246,0,0,0,2,1203,3312,1100,1102,1103,2000
198,YE,1.200709,0,2,1,18,2500,2213,1711,2405,1404,2000
199,ZA,0.855331,44,44,46,24,3302,3310,3322,2302,3603,2000
200,ZM,0.942124,0,0,2,18,1907,3600,2725,2916,2716,2000
201,ZW,1.080258,5,5,14,27,1106,2806,1907,1102,1103,2000

In [48]:
df_interest_metric_collab

,1100,1102,1103,1104,1105,1106,1107,1108,1109,1110,...,3603,3604,3605,3607,3608,3609,3611,3612,3614,3616
country,,,,,,,,,,,,,,,,,,,,,
AE,NaN,2.552185,NaN,NaN,NaN,0.728239,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.867658,1.098190,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
YE,NaN,NaN,NaN,NaN,2.269149,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZA,0.155831,1.181772,0.680572,NaN,1.324993,-0.236709,NaN,NaN,0.301641,0.364754,...,1.922775,NaN,1.664946,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.791337,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZW,NaN,2.582038,2.486303,2.182823,0.528034,2.955316,NaN,NaN,1.414225,0.337904,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
df_interest_metric_indiv

,1100,1102,1103,1104,1105,1106,1107,1108,1109,1110,...,3603,3604,3605,3607,3608,3609,3611,3612,3614,3616
country,,,,,,,,,,,,,,,,,,,,,
AE,NaN,NaN,0.912045,NaN,NaN,NaN,NaN,NaN,0.702021,-1.085632,...,NaN,NaN,NaN,NaN,NaN,NaN,1.723116,NaN,NaN,1.450400
AF,NaN,3.523667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.421254,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AL,NaN,NaN,NaN,NaN,NaN,3.027534,NaN,NaN,NaN,1.777929,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AM,NaN,NaN,NaN,1.338619,NaN,0.012933,NaN,NaN,NaN,-0.543525,...,NaN,0.972281,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
YE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZA,0.763845,1.203001,1.331879,0.928664,1.176732,0.178343,1.557272,2.46014,0.651851,0.283283,...,NaN,-0.025461,-0.133247,NaN,1.577751,0.872607,0.574334,NaN,0.130156,0.771622
ZM,NaN,2.864421,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.762008,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZW,NaN,2.470517,2.365781,2.943395,NaN,1.617709,NaN,NaN,NaN,0.368104,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
df_interest_metric_stats_collab = uf.get_interest_metric_stats(df_interest_metric_collab, df_subfield_stats_collab, year)
df_interest_metric_stats_indiv = uf.get_interest_metric_stats(df_interest_metric_indiv, df_subfield_stats_indiv, year)

In [53]:
df_distance_collab = uf.get_cosine_distances(df_interest_metric_collab.fillna(0))
df_distance_indiv = uf.get_cosine_distances(df_interest_metric_indiv.fillna(0))

/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b

In [54]:
df_distance_stats_collab = uf.get_distance_stats(df_distance_collab, year=year)
df_distance_stats_indiv = uf.get_distance_stats(df_distance_indiv, year=year)

# Pipeline

In [57]:
path = uf.PATH + "df_country_subfield/"

df_country_stats_list = []
df_subfield_stats_collab_list = []
df_subfield_stats_individual_list = []
df_interest_metric_stats_collab_list = []
df_interest_metric_stats_individual_list = []
df_distance_stats_collab_list = []
df_distance_stats_individual_list = []

for year in tqdm(np.arange(1970, 2024)):
    df_country_subfield_collab = pd.read_csv(path+""+str(year)+".csv", index_col=0)
    df_country_subfield_individual = pd.read_csv(path+"individual_"+str(year)+".csv", index_col=0)

    df_country_stats_collab = uf.get_country_stats(df_country_subfield_collab)
    df_country_stats_individual = uf.get_country_stats(df_country_subfield_individual)

    col_list_coupled = [[col+"_collab", col+"_individual"] for col in df_country_stats_collab.columns.to_list()]
    col_list = [x for sublist in col_list_coupled for x in sublist]

    df_country_stats_compare = (
        df_country_stats_collab
        .merge(df_country_stats_individual, left_index=True, right_index=True, how="outer", suffixes=("_collab", "_individual"))
        [col_list]
        .assign(year=year)
        .reset_index()
    )

    df_interest_metric_collab = uf.get_interest_metric(df_country_subfield_collab)
    df_interest_metric_individual = uf.get_interest_metric(df_country_subfield_individual)

    df_subfield_stats_collab = uf.get_subfield_stats(df_country_subfield_collab, df_interest_metric_collab, year)
    df_subfield_stats_individual = uf.get_subfield_stats(df_country_subfield_individual, df_interest_metric_individual, year)

    df_interest_metric_stats_collab = uf.get_interest_metric_stats(df_interest_metric_collab, df_subfield_stats_collab, year)
    df_interest_metric_stats_individual = uf.get_interest_metric_stats(df_interest_metric_individual, df_subfield_stats_individual, year)

    df_distance_collab = uf.get_cosine_distances(df_interest_metric_collab.fillna(0))
    df_distance_individual = uf.get_cosine_distances(df_interest_metric_individual.fillna(0))

    df_distance_stats_collab = uf.get_distance_stats(df_distance_collab, year=year)
    df_distance_stats_individual = uf.get_distance_stats(df_distance_individual, year=year)

    df_country_stats_list.append(df_country_stats_compare)
    df_subfield_stats_collab_list.append(df_subfield_stats_collab)
    df_subfield_stats_individual_list.append(df_subfield_stats_individual)
    df_interest_metric_stats_collab_list.append(df_interest_metric_stats_collab)
    df_interest_metric_stats_individual_list.append(df_interest_metric_stats_individual)
    df_distance_stats_collab_list.append(df_distance_stats_collab)
    df_distance_stats_individual_list.append(df_distance_stats_individual)

    df_interest_metric_collab.to_csv(uf.PATH+f"cosine_pipeline/df_interest_metric/collab_{year}.csv")
    df_interest_metric_individual.to_csv(uf.PATH+f"cosine_pipeline/df_interest_metric/individual_{year}.csv")
    df_distance_collab.to_csv(uf.PATH+f"cosine_pipeline/df_distance/collab_{year}.csv")
    df_distance_individual.to_csv(uf.PATH+f"cosine_pipeline/df_distance/individual_{year}.csv")

df_country_stats_compare = pd.concat(df_country_stats_list)
df_subfield_stats_collab = pd.concat(df_subfield_stats_collab_list)
df_subfield_stats_individual = pd.concat(df_subfield_stats_individual_list)
df_interest_metric_stats_collab = pd.concat(df_interest_metric_stats_collab_list)
df_interest_metric_stats_individual = pd.concat(df_interest_metric_stats_individual_list)
df_distance_stats_collab = pd.concat(df_distance_stats_collab_list)
df_distance_stats_individual = pd.concat(df_distance_stats_individual_list)

df_country_stats_compare.to_csv(uf.PATH+f"cosine_pipeline/df_country_stats_compare.csv", index=False)
df_subfield_stats_collab.to_csv(uf.PATH+f"cosine_pipeline/df_subfield_stats_collab.csv", index=False)
df_subfield_stats_individual.to_csv(uf.PATH+f"cosine_pipeline/df_subfield_stats_individual.csv", index=False)
df_interest_metric_stats_collab.to_csv(uf.PATH+f"cosine_pipeline/df_interest_metric_stats_collab.csv", index=False)
df_interest_metric_stats_individual.to_csv(uf.PATH+f"cosine_pipeline/df_interest_metric_stats_individual.csv", index=False)
df_distance_stats_collab.to_csv(uf.PATH+f"cosine_pipeline/df_distance_stats_collab.csv", index=False)
df_distance_stats_individual.to_csv(uf.PATH+f"cosine_pipeline/df_distance_stats_individual.csv", index=False)

  0%|          | 0/54 [00:00<?, ?it/s]/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
  2%|▏         | 1/54 [00:00<00:15,  3.52it/s]/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
  4%|▎         | 2/54 [00:00<00:13,  3.80it/s]/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
  6%|▌         | 3/54 [00:00<00:13,  3.81it/s]/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
  7%|▋         | 4/54 [00:01<00:13,  3.71it/s]/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
  9%|▉         | 5/54 [00:01<00:13,  3.70it/s]/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
 11%|█         | 6/54 [00:01<00:13,  3.69it/s]/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
 13%|█▎        | 7/54 [00:01<00:12,  3.71it/s]/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
 15%|█▍        | 8/54 [00:02<00:12,  3.68it/s]/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
 17%|█▋        | 9/54 [00:02<00:12,  3.67it/s]/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
 19%|█▊        | 10/54 [00:02<00:12,  3.61it/s]/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
 20%|██        | 11/54 [00:03<00:11,  3.59it/s]/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
 22%|██▏       | 12/54 [00:03<00:11,  3.55it/s]/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
 24%|██▍       | 13/54 [00:03<00:11,  3.48it/s]/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
 26%|██▌       | 14/54 [00:03<00:11,  3.44it/s]/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
 28%|██▊       | 15/54 [00:04<00:11,  3.43it/s]/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
 30%|██▉       | 16/54 [00:04<00:11,  3.41it/s]/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
 31%|███▏      | 17/54 [00:04<00:11,  3.20it/s]/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
 33%|███▎      | 18/54 [00:05<00:11,  3.22it/s]/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
 35%|███▌      | 19/54 [00:05<00:10,  3.23it/s]/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/irinavorobeva/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b