In [15]:
import pandas as pd

import plotly.express as px

import irina.utility_functions as uf

In [5]:
pd.read_csv(uf.PATH+f"df_jaccard_dist_yearly_collaborative.csv")

      year country  from_start      diag
0     1970      AE    0.000000  0.000000
1     1971      AE    0.916667  0.916667
2     1972      AE    0.900000  1.000000
3     1973      AE    0.818182  0.800000
4     1974      AE    1.000000  0.800000
...    ...     ...         ...       ...
9918  2019      TL    1.000000  0.852941
9919  2020      TL    1.000000  0.774194
9920  2021      TL    1.000000  0.789474
9921  2022      TL    1.000000  0.770833
9922  2021      EH    0.000000  0.000000

[9923 rows x 4 columns]

In [38]:
dist_types = ["w1", "jaccard"]
modes = ["individual", "collaborative"]

df_dist_years_list = []
for dist in dist_types:
    for mode in modes:
        df_dist_years_list.append(
            pd.read_csv(uf.PATH+f"df_{dist}_dist_yearly_{mode}.csv").rename(columns={"index": "year"}).assign(
                mode=mode, dist=dist)
        )
df_dist_years = pd.concat(df_dist_years_list)

In [39]:
df_dist_years

      year country  from_start      diag           mode     dist
0     1970      AE    0.000000  0.000000     individual       w1
1     1971      AE    0.491786  0.491786     individual       w1
2     1972      AE    0.511223  0.127980     individual       w1
3     1973      AE    0.320180  0.241239     individual       w1
4     1974      AE    0.505034  0.231754     individual       w1
...    ...     ...         ...       ...            ...      ...
9918  2019      TL    1.000000  0.852941  collaborative  jaccard
9919  2020      TL    1.000000  0.774194  collaborative  jaccard
9920  2021      TL    1.000000  0.789474  collaborative  jaccard
9921  2022      TL    1.000000  0.770833  collaborative  jaccard
9922  2021      EH    0.000000  0.000000  collaborative  jaccard

[40336 rows x 6 columns]

In [42]:
country_list = df_dist_years["country"].drop_duplicates().sample(5)
country_list = ["US", "CN", "ID", "IN"]
px.line(
    (
        df_dist_years
        .query("country in @country_list")
    ),
    x="year",
    y="diag",
    color="country",
    hover_data=["mode", "dist"],
)

In [50]:
df_stats = pd.read_csv(uf.PATH+"df_country_stats_yearly.csv")

In [51]:
df_stats.head()

,country,mode,year,entropy,norm_entropy,total_articles,log_total_articles,gini
0,AE,individual,1970,2.740875,0.496045,34.0,3.526361,0.323529
1,AF,individual,1970,1.609438,0.291277,5.0,1.609438,0.000000
2,AM,individual,1970,3.126757,0.565882,65.0,4.174387,0.383333
3,AO,individual,1970,0.693147,0.125446,2.0,0.693147,0.000000
4,AR,individual,1970,4.278805,0.774381,873.0,6.771936,0.600798

In [52]:
country = "AE"
df_stats.query("country == @country")

,country,mode,year,entropy,norm_entropy,total_articles,log_total_articles,gini
0,AE,individual,1970,2.740875,0.496045,34.0,3.526361,0.323529
173,AE,collaborative,1970,2.163956,0.400201,10.0,2.302585,0.088889
324,AE,individual,1971,2.273212,0.411407,29.0,3.367296,0.397878
489,AE,collaborative,1971,1.386294,0.257902,4.0,1.386294,0.000000
616,AE,individual,1972,2.771928,0.501665,31.0,3.433987,0.288625
...,...,...,...,...,...,...,...,...
19089,AE,collaborative,2020,4.614476,0.834530,5936.0,8.688791,0.647890
19306,AE,individual,2021,4.636234,0.838465,3923.0,8.274612,0.630564
19521,AE,collaborative,2021,4.645021,0.840054,7247.0,8.888343,0.642084
19738,AE,individual,2022,4.641234,0.839369,4503.0,8.412499,0.625381
19952,AE,collaborative,2022,4.612553,0.834182,8458.0,9.042868,0.650568

In [54]:
df_dist_stats = (
    df_dist_years
    .merge(df_stats, on=["year", "country", "mode"])
)

In [66]:
df_dist_stats.query("dist == \"w1\"")[["diag", "from_start", "total_articles", "log_total_articles", "gini"]].corr()

,diag,from_start,total_articles,log_total_articles,gini
diag,1.000000,0.500572,-0.121365,-0.657533,-0.665799
from_start,0.500572,1.000000,-0.124394,-0.473308,-0.456892
total_articles,-0.121365,-0.124394,1.000000,0.364879,0.216590
log_total_articles,-0.657533,-0.473308,0.364879,1.000000,0.930733
gini,-0.665799,-0.456892,0.216590,0.930733,1.000000

In [65]:
px.scatter(
    df_dist_stats.query("dist == \"w1\""),
    x="diag",
    y="gini",
    color="mode",
)

In [74]:
df_pct = (
    df_dist_years
    .sort_values(["country", "mode", "dist", "year"])
    .groupby(["country", "mode", "dist"], as_index=False)
    .apply(lambda g: g.assign(
        pct_change=g.diag.pct_change()
    ))
    .reset_index(drop=True)
)

/var/folders/kq/3vlmcmh917x4z481rl4yj6t00000gn/T/ipykernel_1168/151026444.py:2: FutureWarning:

DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.

In [76]:
df_pct

       year country  from_start      diag           mode     dist  pct_change
0      1993      AD    0.000000  0.000000  collaborative  jaccard         NaN
1      2001      AD    1.000000  1.000000  collaborative  jaccard         inf
2      2002      AD    1.000000  1.000000  collaborative  jaccard    0.000000
3      2003      AD    1.000000  1.000000  collaborative  jaccard    0.000000
4      2004      AD    1.000000  1.000000  collaborative  jaccard    0.000000
...     ...     ...         ...       ...            ...      ...         ...
40331  2018      ZW    0.557004  0.073172     individual       w1   -0.112016
40332  2019      ZW    0.570317  0.037844     individual       w1   -0.482800
40333  2020      ZW    0.552649  0.040251     individual       w1    0.063593
40334  2021      ZW    0.579648  0.073581     individual       w1    0.828037
40335  2022      ZW    0.593042  0.037863     individual       w1   -0.485423

[40336 rows x 7 columns]

['US',
 'CN',
 'GB',
 'DE',
 'CA',
 'AU',
 'IT',
 'FR',
 'ES',
 'IN',
 'JP',
 'NL',
 'SA',
 'BR',
 'CH',
 'KR',
 'SE',
 'PK',
 'IR',
 'RU',
 'BE',
 'MY',
 'DK',
 'EG',
 'PL',
 'TR',
 'AT',
 'HK',
 'PT',
 'TW',
 'NO',
 'SG',
 'MX',
 'FI',
 'ID',
 'ZA',
 'CZ',
 'IL',
 'IE',
 'GR',
 'CL',
 'NZ',
 'TH',
 'AE',
 'NG',
 'CO',
 'VN',
 'BD',
 'AR',
 'HU',
 'UA',
 'RO',
 'IQ',
 'TN',
 'JO',
 'DZ',
 'QA',
 'MA',
 'RS',
 'SK',
 'MO',
 'ET',
 'EC',
 'KZ',
 'HR',
 'SI',
 'PE',
 'CY',
 'GH',
 'KE',
 'LB',
 'PH',
 'BG',
 'EE',
 'UG',
 'LT',
 'OM',
 'LU',
 'NP',
 'KW',
 'LK',
 'TZ',
 'CM',
 'BY',
 'UY',
 'IS',
 'CR',
 'LV',
 'SD',
 'YE',
 'PR',
 'UZ',
 'CU',
 'AZ',
 'PS',
 'BH',
 'BA',
 'VE',
 'KH',
 'ZW',
 'TJ',
 'BN',
 'ZM',
 'MK',
 'SS',
 'MN',
 'RW',
 'MW',
 'SN',
 'MT',
 'BJ',
 'MZ',
 'BF',
 'PA',
 'GE',
 'AM',
 'CD',
 'CI',
 'BO',
 'BW',
 'LY',
 'SY',
 'AL',
 'KG',
 'AF',
 'PY',
 'GT',
 'FJ',
 'MD',
 'ME',
 'MM',
 'ML',
 'MG',
 'DO',
 'BI',
 'GD',
 'TT',
 'CG',
 'GM',
 'AG',
 'HN',
 'TG',
 'JM',
 'MU',
 'NE',
 'PG',
 'RE',
 'VG',
 'AO',
 'LA',
 'NI',
 'SL',
 'GP',
 'LI',
 'SV',
 'MC',
 'BB',
 'GA',
 'KN',
 'FO',
 'NC',
 'BT',
 'SZ',
 'PF',
 'TD',
 'ST',
 'SO',
 'GL',
 'GU',
 'GF',
 'LS',
 'MQ',
 'GN',
 'KY',
 'MV',
 'HT',
 'TL',
 'CF',
 'LR',
 'VI',
 'CV',
 'GW',
 'MR',
 'BS',
 'BM',
 'WS',
 'GY',
 'SC',
 'TM',
 'AW',
 'BZ',
 'PW',
 'AD',
 'ER',
 'VU',
 'SR',
 'DJ',
 'SM',
 'TO',
 'DM',
 'FK',
 'MP',
 'KP',
 'SJ',
 'LC',
 'GQ',
 'MS',
 'VA',
 'KI',
 'AS',
 'GI',
 'FM',
 'TC',
 'SB',
 'VC',
 'NU',
 'TV']

In [94]:
df_plot

country,year,US,CN,GB,DE,CA,AU,IT,FR,ES,...,VA,KI,AS,GI,FM,TC,SB,VC,NU,TV
0,1970,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1971,0.167421,0.757576,0.276382,0.366412,0.338889,0.507246,0.532710,0.520325,0.821053,...,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
2,1972,0.155251,0.666667,0.278049,0.404110,0.312849,0.462069,0.537736,0.537879,0.622642,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1973,0.152466,0.672131,0.204878,0.360759,0.303191,0.425806,0.481818,0.446970,0.678571,...,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN
4,1974,0.165217,0.590909,0.221154,0.370370,0.234043,0.450000,0.440367,0.478873,0.689655,...,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN
5,1975,0.106195,0.567901,0.240566,0.363636,0.250000,0.390244,0.486957,0.426752,0.731343,...,NaN,NaN,NaN,1.000000,NaN,NaN,1.00,NaN,0.0,NaN
6,1976,0.137339,0.600000,0.254545,0.262195,0.234375,0.403509,0.415254,0.318471,0.619718,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1977,0.120690,0.696970,0.186916,0.297143,0.243655,0.311377,0.401515,0.318750,0.631579,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1978,0.100437,0.643564,0.197248,0.267442,0.196970,0.350575,0.392857,0.337423,0.632911,...,0.000000,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN
9,1979,0.135593,0.594059,0.211712,0.219101,0.220588,0.312139,0.330935,0.304878,0.548780,...,NaN,0.000000,1.000000,NaN,NaN,NaN,1.00,NaN,NaN,NaN
10,1980,0.078261,0.590476,0.190045,0.231579,0.221154,0.270270,0.348993,0.283237,0.601942,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1981,0.101695,0.600000,0.132420,0.212435,0.199052,0.278351,0.314103,0.284153,0.536364,...,0.500000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,1982,0.109244,0.530303,0.135135,0.201005,0.215962,0.225806,0.279221,0.263441,0.425926,...,0.500000,NaN,NaN,1.000000,1.000000,NaN,1.00,NaN,NaN,0.000000
13,1983,0.085470,0.434483,0.113636,0.215686,0.146919,0.236842,0.298137,0.263441,0.454545,...,NaN,NaN,NaN,1.000000,NaN,NaN,1.00,NaN,NaN,NaN
14,1984,0.080169,0.358491,0.144105,0.195000,0.167442,0.202073,0.245509,0.224599,0.507576,...,1.000000,1.000000,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN
15,1985,0.075314,0.277778,0.156118,0.183168,0.154206,0.218905,0.254335,0.192708,0.428571,...,1.000000,NaN,NaN,1.000000,1.000000,NaN,NaN,0.000000,NaN,NaN
16,1986,0.063025,0.301205,0.120690,0.177033,0.134259,0.246305,0.259887,0.210256,0.395973,...,0.000000,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN
17,1987,0.054393,0.273810,0.096070,0.125000,0.156951,0.221106,0.260870,0.225490,0.339869,...,0.000000,NaN,NaN,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN
18,1988,0.049793,0.272727,0.104803,0.132701,0.137778,0.235000,0.255319,0.202899,0.370370,...,1.000000,NaN,1.000000,1.000000,1.000000,NaN,NaN,NaN,1.0,NaN
19,1989,0.065574,0.244444,0.088106,0.183857,0.157205,0.205000,0.215054,0.166667,0.353933,...,1.000000,NaN,NaN,0.800000,1.000000,NaN,NaN,NaN,NaN,NaN
20,1990,0.061224,0.243243,0.082969,0.143498,0.111111,0.200957,0.205263,0.149758,0.312849,...,NaN,1.000000,NaN,1.000000,NaN,NaN,1.00,NaN,NaN,NaN
21,1991,0.041152,0.202186,0.076596,0.143498,0.102222,0.198157,0.203046,0.164319,0.247253,...,0.500000,NaN,NaN,1.000000,NaN,NaN,NaN,1.000000,NaN,NaN
22,1992,0.045267,0.206522,0.051502,0.109589,0.097778,0.200000,0.183168,0.146789,0.225641,...,0.000000,NaN,NaN,1.000000,NaN,NaN,1.00,NaN,NaN,NaN
23,1993,0.025105,0.178947,0.056034,0.087963,0.075556,0.181395,0.188119,0.128440,0.255000,...,0.666667,NaN,NaN,0.666667,NaN,NaN,NaN,NaN,NaN,NaN
24,1994,0.041494,0.243902,0.071130,0.103604,0.088496,0.118721,0.221154,0.120370,0.216495,...,1.000000,NaN,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN
25,1995,0.053279,0.175000,0.066667,0.118943,0.096070,0.123894,0.190476,0.105023,0.227723,...,0.000000,NaN,NaN,1.000000,1.000000,NaN,1.00,NaN,NaN,NaN
26,1996,0.032653,0.165049,0.062241,0.079295,0.098712,0.105727,0.197248,0.097778,0.222222,...,1.000000,NaN,NaN,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN
27,1997,0.024291,0.154589,0.057377,0.065502,0.089744,0.092511,0.137615,0.117904,0.210526,...,0.750000,NaN,1.000000,1.000000,NaN,NaN,1.00,1.000000,NaN,NaN
28,1998,0.024390,0.145631,0.045455,0.057522,0.064378,0.087336,0.145455,0.111111,0.186916,...,0.800000,NaN,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,1.000000
29,1999,0.024390,0.127962,0.061224,0.083333,0.052402,0.070175,0.155251,0.084821,0.126168,...,0.500000,NaN,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN
30,2000,0.012195,0.127854,0.056911,0.106838,0.065217,0.074236,0.136364,0.099138,0.140909,...,0.500000,NaN,1.000000,0.909091,NaN,0.000000,NaN,1.000000,NaN,NaN
31,2001,0.008163,0.130045,0.045082,0.068966,0.060086,0.085837,0.137168,0.085837,0.142222,...,1.000000,NaN,1.000000,0.888889,0.666667,1.000000,NaN,NaN,NaN,NaN
32,2002,0.008197,0.144737,0.028926,0.076271,0.047009,0.077253,0.128319,0.101695,0.102679,...,1.000000,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,1.0,NaN
33,2003,0.024194,0.107143,0.040816,0.059322,0.055085,0.061135,0.102222,0.094421,0.089686,...,1.000000,NaN,1.000000,1.000000,1.000000,NaN,NaN,1.000000,NaN,NaN
34,2004,0.008097,0.106195,0.032520,0.051282,0.070833,0.081197,0.082969,0.080851,0.096070,...,0.800000,NaN,1.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN
35,2005,0.008097,0.087336,0.032520,0.050633,0.046025,0.064378,0.085837,0.063025,0.080508,...,0.666667,NaN,0.500000,0.833333,1.000000,NaN,NaN,NaN,NaN,NaN
36,2006,0.016129,0.085837,0.036145,0.053279,0.033473,0.064103,0.092827,0.066667,0.059574,...,0.500000,1.000000,0.500000,1.000000,1.000000,NaN,1.00,1.000000,1.0,1.000000
37,2007,0.020080,0.085470,0.012146,0.048980,0.049383,0.042373,0.059322,0.021186,0.055085,...,0.750000,1.000000,1.000000,1.000000,0.777778,NaN,0.50,NaN,1.0,NaN
38,2008,0.019920,0.092050,0.020325,0.037344,0.048980,0.074074,0.087866,0.041322,0.062241,...,0.714286,NaN,0.916667,0.882353,0.857143,NaN,1.00,NaN,NaN,NaN
39,2009,0.012000,0.061728,0.012195,0.036885,0.040984,0.057377,0.102041,0.012448,0.050000,...,0.909091,NaN,0.777778,0.882353,0.750000,NaN,NaN,1.000000,1.0,1.000000
40,2010,0.008000,0.057613,0.024000,0.036585,0.053279,0.053061,0.053279,0.037037,0.045833,...,0.900000,NaN,0.666667,0.916667,1.000000,NaN,1.00,0.666667,NaN,NaN
41,2011,0.008000,0.041494,0.020000,0.032787,0.032787,0.028807,0.037190,0.036735,0.025000,...,0.857143,1.000000,0.857143,0.909091,1.000000,NaN,1.00,NaN,1.0,NaN
42,2012,0.000000,0.049180,0.008065,0.028689,0.036437,0.036585,0.061224,0.024590,0.048980,...,0.800000,1.000000,0.714286,0.833333,1.000000,NaN,NaN,1.000000,NaN,NaN
43,2013,0.008032,0.049180,0.020080,0.016393,0.012245,0.040486,0.060241,0.020492,0.036885,...,0.909091,1.000000,0.769231,0.812500,1.000000,NaN,1.00,1.000000,NaN,1.000000
44,2014,0.008000,0.044534,0.012048,0.028340,0.024194,0.048980,0.036145,0.028226,0.032787,...,0.923077,0.800000,0.583333,0.941176,0.818182,NaN,1.00,1.000000,1.0,1.000000
45,2015,0.004000,0.024390,0.027888,0.028340,0.024291,0.053279,0.036290,0.024291,0.040650,...,0.900000,0.857143,0.857143,0.812500,0.928571,0.500000,1.00,1.000000,NaN,1.000000
46,2016,0.012000,0.028571,0.016064,0.032389,0.028340,0.028571,0.016393,0.028226,0.040161,...,0.923077,1.000000,0.846154,0.944444,0.923077,NaN,1.00,1.000000,NaN,NaN
47,2017,0.012000,0.032389,0.012048,0.016260,0.020243,0.024390,0.024390,0.028226,0.040323,...,0.769231,1.000000,0.818182,0.933333,0.615385,1.000000,1.00,1.000000,1.0,1.000000
48,2018,0.015873,0.020243,0.016000,0.012195,0.012097,0.020408,0.012146,0.028340,0.024390,...,0.850000,1.000000,0.750000,0.916667,0.764706,1.000000,1.00,0.923077,1.0,0.666667
49,2019,0.011952,0.028112,0.023904,0.020161,0.020161,0.020243,0.012146,0.028000,0.016064,...,0.714286,1.000000,0.636364,0.833333,0.642857,1.000000,0.75,0.909091,NaN,NaN
50,2020,0.008000,0.016194,0.012048,0.016064,0.020243,0.024096,0.020243,0.028000,0.028000,...,0.894737,0.909091,0.769231,0.950000,0.571429,1.000000,1.00,0.900000,1.0,1.000000
51,2021,0.007937,0.008130,0.016000,0.020080,0.020080,0.020000,0.020161,0.024390,0.016194,...,0.733333,1.000000,0.692308,0.900000,0.800000,0.888889,1.00,0.800000,NaN,1.000000
52,2022,0.003968,0.008097,0.016000,0.016129,0.016129,0.008065,0.028000,0.028340,0.020161,...,0.857143,1.000000,0.600000,0.826087,0.888889,1.000000,1.00,1.000000,1.0,1.000000

In [127]:
dist = "w1"
mode = "individual"
country_list = (
    df_stats
    .query("year == 2022 and mode == @mode")
    .sort_values("total_articles", ascending=False)
    .country
    .head(10)
).to_list()
df_plot = (
    df_pct.query("dist == @dist and mode == @mode")
    .pivot(index="year", columns="country", values="diag")
    [country_list]
)
uf.plotly_heatmap(df_plot,
                  x_labels=df_plot.columns,
                  y_labels=df_plot.index,
                  z_min=0, z_max=0.2,
                  x_type="country",
                  colorscale="non",
                  line_height=10,
                  title=f"{dist} {mode}",
                  )

In [126]:
# dist = "jaccard"
# mode = "individual"
# country_list = (
#     df_stats
#     .query("year == 2022 and mode == @mode")
#     .sort_values("total_articles", ascending=False)
#     .country
#     .head(50)
# ).to_list()
# df_plot = (
#     df_stats.query("mode == @mode")
#     .pivot(index="year", columns="country", values="log_total_articles")
#     [country_list]
# )
# uf.plotly_heatmap(df_plot,
#                   x_labels=df_plot.columns,
#                   y_labels=df_plot.index,
#                   # z_min=0, z_max=0.2,
#                   x_type="country",
#                   colorscale="non",
#                   line_height=10,
#                   title=f"Total articles {mode}",
#                   )

In [125]:
country_list = ["CH", "IR", "ID", "CN"]
px.line(
    df_stats.query("country == @country_list and mode == @mode"),
    x="year",
    y="log_total_articles",
    color="country"
)